# Generated by Django 6.0.7 on 2026-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.IntegerField(default=0, help_text='Porcentaje de descuento (ejemplo: 20 para 20%)')),
                ('plataforma', models.CharField(choices=[('PS', 'Playstation'), ('XB', 'Xbox'), ('NT', 'Nintendo'), ('PC', 'PC')], max_length=2)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
