# Generated by Django 6.0.7 on 2026-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='seccion',
            field=models.CharField(choices=[('DEST', 'Juegos Destacados'), ('ACC', 'Acción'), ('ADV', 'Aventura'), ('DEP', 'Deportes')], default='DEST', max_length=4),
        ),
    ]
